**THEORETICAL QUESTIONS**

**1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?**

ans1:-NumPy is a fundamental library in Python for scientific computing. It offers powerful features for working with multidimensional arrays and performing various mathematical operations efficiently.

NumPy (Numerical Python) is an open source Python library that has a wide range of inbuilt functions.

Advantage of Numpy :NumPy is ideal for handling large amounts of homogeneous (same-type) data, offering significant improvements in speed and memory efficiency. It also provides high-level syntax for a wide range of numerical operations, making it a powerful tool for scientific computing and data processing on the CPU.




**2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?**

ans2:-In numpy, np.mean() calculates the arithmetic mean or simple average of an array, while np.average() can compute both simple and weighted averages.

np.mean() can be used if all values in the array have equal importance whereas np.average() is used when different weights to values are assigned, reflecting their relative importance.

**3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.**

ans:-The np.flip() function in numpy can be used to reverse the order of elements in numpy array along a specified axis. For 1D array , the default axis is 0 and for 2D array , axis can be specified along the rows(axis=0) or columns (axis-1).

FOR EXAMPLE:

In [ ]:
#for 1d array
import numpy as np
arr=np.array([1,2,3,4,5])
reversed_arr=np.flip(arr)
print(reversed_arr)

[5 4 3 2 1]


In [ ]:
#for 2d array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
reversed_arr=np.flip(arr,axis=1)
print(reversed_arr)

[[3 2 1]
 [6 5 4]]


**4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.**

ans:- Data types of elements can be determined in numpy arrays by using "dtype" attributes.

FOR EXAMPLE:

In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(a.dtype)

int64


NumPy arrays are homogeneous, meaning all elements have the same data type. This allows NumPy to allocate memory efficiently and store the data in a contiguous block.

NumPy operations are optimized for specific data types. Using the correct data type can lead to faster computations.
Type mismatches can result in unnecessary type conversions, slowing down performance.


**5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

ans:-In NumPy, ndarrays (N-dimensional arrays) are the fundamental data structure for representing and manipulating numerical data. They are essentially multidimensional grids of elements.

Key Features of ndarrays:

Homogeneous Data Type: All elements in an ndarray have the same data type, allowing for efficient storage and operations.
Multidimensional: ndarrays can represent data in multiple dimensions, from 1D arrays (vectors) to 2D arrays (matrices) and beyond.
Fixed Size: Once created, the size of an ndarray is fixed, unlike Python lists which can dynamically grow or shrink.
Element-wise Operations: NumPy provides a wide range of functions for performing element-wise operations on ndarrays, making numerical computations efficient and concise.
Broadcasting: NumPy allows for operations between arrays of different shapes, automatically expanding the smaller array to match the dimensions of the larger array. This feature simplifies many numerical computations.

**6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

ans:-Numpy arrays have large benefits over python lists which includes:

**Data Storage**: NumPy arrays store data in a contiguous block of memory, while Python lists store pointers to objects scattered in memory. This contiguous storage allows for faster access to elements and efficient vectorized operations.

**Data Types**: NumPy arrays are homogeneous, meaning all elements have the same data type. This allows for optimized operations and reduces the overhead of type checking during computations. Python lists can contain elements of different data types, leading to slower performance.


**Vectorization**: NumPy provides a wide range of vectorized operations that can be applied to entire arrays at once. These operations are implemented in optimized C code, resulting in significant speed improvements compared to looping through individual elements in Python lists.

**Broadcasting**: NumPy's broadcasting feature allows for operations between arrays of different shapes, automatically expanding the smaller array to match the dimensions of the larger array. This simplifies many numerical computations and avoids the need for explicit loops.

**Memory Efficiency**: NumPy arrays are more memory-efficient than Python lists, especially for large datasets. This is because NumPy arrays store data in a compact format, while Python lists require additional memory overhead for storing pointers and object metadata.


**7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.**

ans:- vstack is used to stack arrays vertically (row wise). It combines arrays by adding them as new roes on top of each other.

FOR EXAMPLE:-


In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
stacked_arr=np.vstack((arr1,arr2))
print(stacked_arr)

[[1 2 3]
 [4 5 6]]


hstack is used to stack arrays horizontally (column wise). It combines arrays by adding them as new columns next to each other.

FOR EXAMPLE:-

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
stacked_arr=np.hstack((arr1,arr2))
print(stacked_arr)

[1 2 3 4 5 6]


**8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.**

ans:- The purpose of np.fliplr() is to flip an array in the left/right direction, reversing the order of elements along axis 1 (columns).

**effect on array dimensions**

**1d array:-**It reverses the order of 1d array. this is equivalent to using np.flip(array) with no axis specified.

**2d array:-** It flips the columns of a 2d arrat, effectively, mirroring it horizontally.

**higher dimensions:-** It only flips along the second axis (axis 1) and leaves other dimensions unchanged.

FOR EXAMPLE:-

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
flipped_lr=np.fliplr(arr)
print(flipped_lr)

[[3 2 1]
 [6 5 4]]


The purpose of np.flipud() is to flip an array in the up/down direction, reversing the order of elements along axis 0 (rows).

**Effect on Array Dimensions**

**1D Arrays:** flipud() reverses the elements of a 1D array, similar to fliplr() and np.flip(array).

**2D Arrays:** It flips the rows of a 2D array, mirroring it vertically.

**Higher Dimensions:** It only flips along the first axis (axis 0) and keeps other dimensions as they are.

FOR EXAMPLE:-

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
flipped_ud=np.flipud(arr)
print(flipped_ud)


[[4 5 6]
 [1 2 3]]


**9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

ans:-The array_split() method in NumPy is used to split an array into multiple sub-arrays. You can specify the number of sub-arrays you want or the indices where you want to split the array. It's a more general version of the split() method, as it allows for uneven splits, meaning the sub-arrays don't have to be of equal size.

**Handling Uneven Splits**

When you split an array into a number of sub-arrays that doesn't divide evenly into the array's size, array_split() handles it by making some sub-arrays slightly larger or smaller to accommodate the split. It tries to distribute the elements as evenly as possible among the sub-arrays.

FOR EXAMPLE:-


In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
sub_arrays=np.array_split(arr,3)
for sub_array in sub_arrays:
  print(sub_array)

[1 2]
[3 4]
[5 6]


**10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?**

ans:-Vectorization is the process of applying operations to entire arrays instead of individual elements. This eliminates the need for explicit loops in Python, which can be slow. NumPy uses optimized, pre-compiled C code for array operations, making them significantly faster than traditional Python loops.

FOR EXAMPLE:-

In [ ]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=a+b
print(c)

[ 6  8 10 12]


Broadcasting is a powerful mechanism in NumPy that allows operations between arrays of different shapes, as long as their dimensions are compatible. NumPy automatically "stretches" the smaller array to match the shape of the larger array, enabling element-wise operations without explicit copying of data.

In [ ]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
b= np.array([10,20,30])
c=a+b
print(c)

[[11 22 33]
 [14 25 36]]


**PRACTICAL QUESTIONS**

**1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns**

In [ ]:
import numpy as np
arr1= np.random.randint(1,100,size=(3,3))
print(arr1)
arr1.T    #to interchange rows and columns

[[73  1 85]
 [60 36 27]
 [28 57 67]]


array([[73, 60, 28],
       [ 1, 36, 57],
       [85, 27, 67]])

**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

In [ ]:
import numpy as np
arr1=np.arange(10)
print(arr1)
arr2=arr1.reshape(2,5)
print(arr2)
arr3=arr2.reshape(5,2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [ ]:
import numpy as np
arr1= np.random.rand(4,4)
print(arr1)
array_6x6=np.zeros((6,6))
array_6x6[1:5,1:5]= arr1
print(array_6x6)

[[0.30986756 0.57330053 0.50193457 0.8956695 ]
 [0.99801007 0.78126596 0.32738046 0.76878754]
 [0.62402235 0.41688417 0.23750444 0.49441682]
 [0.18013671 0.54802252 0.92703569 0.48395531]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.30986756 0.57330053 0.50193457 0.8956695  0.        ]
 [0.         0.99801007 0.78126596 0.32738046 0.76878754 0.        ]
 [0.         0.62402235 0.41688417 0.23750444 0.49441682 0.        ]
 [0.         0.18013671 0.54802252 0.92703569 0.48395531 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [ ]:
import numpy as np
arr= np.arange(10,60,5)
print(arr)

[10 15 20 25 30 35 40 45 50 55]


**5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.**

In [ ]:
import numpy as np
arr= np.array(['python', 'numpy','pandas' ])
print(np.char.upper(arr))
print(np.char.lower(arr))
print(np.char.title(arr))

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


**6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**


In [2]:
import numpy as np
def add_space(word):
  return " ".join(word)
arr= np.array(['pw','skills','data','science'])
spaced_words=np.vectorize(add_space)(arr)
print(spaced_words)


['p w' 's k i l l s' 'd a t a' 's c i e n c e']


**7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**


In [8]:
import numpy as np
arr_1= np.array([[10,20,30,40],[50,60,70,80]])
arr_2= np.array([[1,2,3,4],[5,6,7,8]])
print(arr_1+arr_2)
print(arr_1-arr_2)
print(arr_1*arr_2)
print(arr_1/arr_2)

[[11 22 33 44]
 [55 66 77 88]]
[[ 9 18 27 36]
 [45 54 63 72]]
[[ 10  40  90 160]
 [250 360 490 640]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]]


**8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**


In [11]:
import numpy as np
arr_im=np.eye(5)
print(arr_im)
diagonal_elements=np.diag(arr_im)
print(diagonal_elements)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.**

In [15]:
import numpy as np
def is_prime(n):
  if n <=1:
    return False
  for i in range(2,int(n**0.5)+1):
    if n%i==0:
      return False
  return True
arr1= np.random.randint(1,1000, size=(10,10))
prime_numbers=[num for num in arr1.flatten() if is_prime(num)]
print(prime_numbers)

[np.int64(409), np.int64(941), np.int64(29), np.int64(61), np.int64(487), np.int64(23), np.int64(173), np.int64(443), np.int64(41), np.int64(479), np.int64(641), np.int64(683), np.int64(101), np.int64(229), np.int64(313), np.int64(499), np.int64(631), np.int64(263), np.int64(733), np.int64(379), np.int64(641)]


**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.**


In [18]:
import numpy as np
temperatures= np.random.randint(20,35, size=30)
num_full_weeks= len(temperatures)//7
remaining_days= len(temperatures)%7
weekly_temperatures=temperatures[:num_full_weeks*7].reshape(num_full_weeks,7)
weekly_averages=np.mean(weekly_temperatures,axis=1)
if remaining_days>0:
  remaining_avg=np.mean(temperatures[num_full_weeks*7:])
  print('average of remaining days:', remaining_avg)
print('weekly averages:', weekly_averages)



average of remaining days: 24.5
weekly averages: [26.71428571 30.14285714 26.57142857 27.57142857]
